### ISSUE TITLE
openGgpkPath doesn't work with Windows absolute path

### ISSUE THREAD

**Issue by SnosMe** [oriath-net/pogo#1]
"C:/Program Files (x86)/Grinding Gear Games/Path of Exile/Content.ggpk:Data/ActiveSkills.dat"

is split in 3 parts

- C
- /Program Files (x86)/Grinding Gear Games/Path of Exile/Content.ggpk
- Data/ActiveSkills.da

**Comment by duskwuff** [comment]
Whoops. Guess that's what I get for doing all my testing in WSL.

Fixed.
